### ISSUE TITLE
Documentation. 

### ISSUE THREAD

**Issue by omideleayo** [YoeriNijs/NoteBuddy#6]
Hi, 
May I send you some interesting documentation for this project, like FAQ?

**Comment by YoeriNijs** [comment]
Hi Omideleayo,

Could you please elaborate on this? It is unclear to me whether you wish to send documentation about encrypted software in general or NoteBuddy in particular. For the latter, you are free to create a pull request :)

**Comment by omideleayo** [comment]
About NoteBuddy.
I would proceed with a pull request as soon as am done with the document. 
Thanks

**Comment by YoeriNijs** [comment]
Great, looking forward to it!

**Comment by omideleayo** [comment]
To complete my documentation.
May I ask,  why the name  "NoteBuddy"

**Comment by YoeriNijs** [comment]
Because it sounds nice :) And the app should help one as a friend to create notes easily.

**Comment by omideleayo** [comment]
Cool, thanks

**Comment by omideleayo** [comment]
One last thing. 
What sort of encryption is NoteBuddy based on.

**Comment by omideleayo** [comment]
Enwokoma, please what's funny? From the statement

**Comment by omideleayo** [comment]
Cool,  exactly what I needed, and am done with the FAQs documentation.
Once am free would make some proofreading and make a PR.

**Comment by enwokoma** [comment]
@omideleayo. Nothing serious!

**Comment by YoeriNijs** [comment]
Merged in https://github.com/YoeriNijs/NoteBuddy/pull/8
