### ISSUE TITLE
NB-1000: Can't create backup

### ISSUE THREAD

**Issue by princekelly1** [YoeriNijs/NoteBuddy#7]
Can't create note backup. 
It's saying no note available while there are lots of notes in it.

**Comment by YoeriNijs** [comment]
Do you granted permission to NoteBuddy to store the lost externally?

**Comment by princekelly1** [comment]
Yes I did

**Comment by YoeriNijs** [comment]
That's odd. You can see the content of the notes, though?

**Comment by princekelly1** [comment]
Yes

**Comment by YoeriNijs** [comment]
It might have something to do with the latest Android release. I will dive into this.

**Comment by princekelly1** [comment]
OK,  cool. 
My android version is 7.0

**Comment by YoeriNijs** [comment]
Fixed in https://github.com/YoeriNijs/NoteBuddy/commit/41b38f64279dfd66d744fa6876a723303754de67
